export const skills = [
  { name: 'JavaScript',          level: 90, ico: 'JS' },
  { name: 'React.js',            level: 85, ico: '⚛'  },
  { name: 'Java',                level: 85, ico: '☕'  },
  { name: 'SQL / MySQL',         level: 85, ico: '🗄'  },
  { name: 'Python',              level: 80, ico: '🐍'  },
  { name: 'Node.js / Express',   level: 80, ico: '🟢'  },
  { name: 'PHP / Laravel',       level: 78, ico: '🌀'  },
  { name: 'Flask',               level: 76, ico: '⚗'  },
  { name: 'MongoDB',             level: 75, ico: '🍃'  },
  { name: 'PyTorch / TensorFlow',level: 72, ico: '🧠'  },
  { name: 'AWS',                 level: 70, ico: '☁'  },
  { name: 'C# / .NET',          level: 75, ico: '#'   },
];

export const projects = [
  {
    id: 1,
    cat: 'MERN',
    e: '💳',
    title: 'PayPilot — Smart Billing System',
    desc: 'Full-stack billing & payment management with invoice generation, subscription tracking, analytics dashboard, and role-based access control.',
    tech: ['MongoDB', 'Express', 'React', 'Node.js'],
    gh: 'https://github.com/devansh698/PayPilot-smart-billing-management-system',
  },
  {
    id: 2,
    cat: 'MERN',
    e: '🏠',
    title: 'Property Rental Platform',
    desc: 'End-to-end property listing platform with search filters, booking management, real-time availability, and separate tenant/landlord portals.',
    tech: ['MongoDB', 'Express', 'React', 'Node.js'],
    gh: 'https://github.com/devansh698/Property-Rental',
  },
  {
    id: 3,
    cat: 'MERN',
    e: '✅',
    title: 'To-Do List App',
    desc: 'Full-stack task manager with priority levels, due dates, drag-and-drop reordering, categories, and JWT-based user authentication.',
    tech: ['MongoDB', 'Express', 'React', 'Node.js'],
    gh: 'https://github.com/devansh698/To-Do-List',
  },
  {
    id: 4,
    cat: 'Laravel',
    e: '📦',
    title: 'Warehouse Management System',
    desc: 'Enterprise WMS with inventory tracking, order fulfilment, barcode scanning, supplier management, and real-time reporting dashboards.',
    tech: ['Laravel', 'PHP', 'MySQL', 'React'],
    gh: '#',
  },
  {
    id: 5,
    cat: 'Web',
    e: '🏪',
    title: 'E-Commerce Platform',
    desc: 'Scalable marketplace with real-time inventory, Stripe payments, wishlist, reviews system, and a full-featured admin analytics dashboard.',
    tech: ['React', 'Node.js', 'MongoDB', 'Stripe'],
    gh: '#',
  },
  {
    id: 6,
    cat: 'Web',
    e: '🌤',
    title: 'Weather App',
    desc: 'Real-time weather app with location search, 7-day forecast, animated condition icons, and hourly temperature charts.',
    tech: ['React', 'Node.js', 'OpenWeather API', 'CSS'],
    gh: 'https://github.com/devansh698/Weather-App',
  },
  {
    id: 7,
    cat: 'Web',
    e: '☕',
    title: 'Cafe Website',
    desc: 'Responsive cafe web app with interactive menu, reservation system, gallery, customer testimonials, and smooth scroll animations.',
    tech: ['React', 'Node.js', 'MongoDB', 'CSS'],
    gh: 'https://github.com/devansh698/Cafe-Website',
  },
];

export const specializations = [
  { ico: '📊', title: 'Foundations of Marketing Analytics',         org: 'Emory University',          url: 'https://www.coursera.org/account/accomplishments/specialization/BUFU2ABGFXX5' },
  { ico: '☕', title: 'Java FullStack Developer',                   org: 'Board Infinity',             url: 'https://www.coursera.org/account/accomplishments/specialization/EQLNTGS7BMCU' },
  { ico: '🤖', title: 'IBM Machine Learning',                       org: 'IBM',                        url: 'https://www.coursera.org/account/accomplishments/professional-cert/FQR1P1VD7CR7' },
  { ico: '🔬', title: 'AI for Scientific Research',                 org: 'LearnQuest',                 url: 'https://www.coursera.org/account/accomplishments/specialization/X5RAKDY7ROIQ' },
  { ico: '🏥', title: 'Health Informatics',                         org: 'Johns Hopkins University',   url: 'https://www.coursera.org/account/accomplishments/specialization/BGQXQQNXPV7C' },
  { ico: '🔥', title: 'IBM Deep Learning with PyTorch, Keras & TF', org: 'IBM',                        url: 'https://www.coursera.org/account/accomplishments/professional-cert/5JSE4KFH7WPD' },
  { ico: '🌲', title: 'Data Structures & Algorithms',               org: 'UC San Diego',               url: 'https://www.coursera.org/account/accomplishments/specialization/XDIRQ4W55TVQ' },
  { ico: '⚙',  title: 'IBM AI Enterprise Workflow',                 org: 'IBM',                        url: 'https://www.coursera.org/account/accomplishments/specialization/J5B8LHXDE0KG' },
  { ico: '☁',  title: 'AWS Fundamentals',                           org: 'Amazon Web Services',        url: 'https://www.coursera.org/account/accomplishments/specialization/ZZL0Q78PJ3YJ' },
  { ico: '🧠', title: 'AI Foundations for Everyone',                org: 'IBM',                        url: 'https://www.coursera.org/account/accomplishments/specialization/GFOG0RRQB87M' },
  { ico: '📋', title: 'Software Product Management',                org: 'University of Alberta',      url: 'https://www.coursera.org/account/accomplishments/specialization/031TKK6B9P0M' },
];

export const courses = [
  { t: 'Capstone: Advanced AI for Drug Discovery',    o: 'LearnQuest',           g: '100%',   url: 'https://www.coursera.org/account/accomplishments/records/LDFGEJN1YJBC' },
  { t: 'Introduction to Data Science & scikit-learn', o: 'LearnQuest',           g: '95.50%', url: 'https://www.coursera.org/account/accomplishments/records/8ZRPUFDNKULW' },
  { t: 'Client Needs and Software Requirements',      o: 'Univ. of Alberta',     g: '93.25%', url: 'https://www.coursera.org/account/accomplishments/records/DPNFAT53DYP1' },
  { t: 'Reviews & Metrics for Software Improvements', o: 'Univ. of Alberta',     g: '96.25%', url: 'https://www.coursera.org/account/accomplishments/records/6A9E62XOUB0F' },
  { t: 'Intro to Software Product Management',        o: 'Univ. of Alberta',     g: '90.17%', url: 'https://www.coursera.org/account/accomplishments/records/IU4TMEMHFQ3T' },
  { t: 'Software Processes and Agile Practices',      o: 'Univ. of Alberta',     g: '95.90%', url: 'https://www.coursera.org/account/accomplishments/records/GGZMAAOLVW0Q' },
  { t: 'AI Capstone Project with Deep Learning',      o: 'IBM',                  g: '95.75%', url: 'https://www.coursera.org/account/accomplishments/records/K2WC8LT35IXO' },
  { t: 'Neural Networks and Random Forests',          o: 'LearnQuest',           g: '95%',    url: 'https://www.coursera.org/account/accomplishments/records/7TB5OHLC3Y4M' },
  { t: 'Agile Planning for Software Products',        o: 'Univ. of Alberta',     g: '97.14%', url: 'https://www.coursera.org/account/accomplishments/records/8ZYDDHRB93MI' },
  { t: 'Machine Learning Models in Science',          o: 'LearnQuest',           g: '98%',    url: 'https://www.coursera.org/account/accomplishments/records/MF1IUEPAHU8Q' },
];

export const badges = [
  { t: 'Google Analytics for Beginners',          o: 'Google',                    url: 'https://analytics.google.com/analytics/academy/' },
  { t: 'Foundations of Cybersecurity',             o: 'Google · Coursera',         url: 'https://www.coursera.org/' },
  { t: 'Cybersecurity Essentials',                 o: 'Cisco Networking Academy',  url: 'https://www.netacad.com/' },
  { t: 'Introduction to AI',                       o: 'IBM · Coursera',            url: 'https://www.coursera.org/' },
  { t: 'Generative AI: Introduction & Applications', o: 'IBM · Coursera',          url: 'https://www.coursera.org/' },
  { t: 'AI-Powered Chatbots Without Programming',  o: 'IBM · Coursera',            url: 'https://www.coursera.org/' },
  { t: 'REST API (Intermediate)',                   o: 'HackerRank',                url: 'https://www.hackerrank.com/certificates/' },
  { t: 'C# (Basic)',                               o: 'HackerRank',                url: 'https://www.hackerrank.com/certificates/' },
  { t: 'SQL',                                      o: 'HackerRank',                url: 'https://www.hackerrank.com/certificates/' },
  { t: 'React',                                    o: 'HackerRank',                url: 'https://www.hackerrank.com/certificates/' },
];
